apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cq6m32343-go 
  janus-idp.io/tekton: cq6m32343-go
  backstage.io/kubernetes-id: cq6m32343-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cq6m32343-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml