apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cq6m32343-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cq6m32343-go 
  name: cq6m32343-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cq6m32343-go 
